*PANTALLA DE SELECCION

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-001.

SELECT-OPTIONS: p_airpto FOR sairport-id.

SELECTION-SCREEN END OF BLOCK b1.


SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-002.

PARAMETERS: r_opc1 RADIOBUTTON GROUP r1, "Imprimir write
            r_opc2 RADIOBUTTON GROUP r1. "Imprimir ALV

SELECTION-SCREEN END OF BLOCK b2.